version: '3.5'
services:
  nginx:
    container_name: ${NAME}_nginx
    image: ${NAME}_nginx
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    working_dir: /var/www
    volumes:
      - ${LARAVEL_PATH}:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT}:80
    networks:
      - internal
  php:
    container_name: ${NAME}_php
    image: ${NAME}_php
    build:
      context: .
      dockerfile: php/php${PHP_VERSION}.Dockerfile
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    working_dir: /var/www
    volumes:
      - ${LARAVEL_PATH}:/var/www
    networks:
      - internal
  mysql:
    container_name: ${NAME}_mysql
    image: ${NAME}_mysql
    build:
      context: .
      dockerfile: mysql/mysql${MYSQL_VERSION}.Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - internal
volumes:
  mysql_data:
      name: ${NAME}_mysql_data
networks:
  internal:
    name: ${NAME}_network
    driver: bridge
